Build binary for darwin
src-d/code-annotation pull request #204
Opened 2018-03-06 10:54 UTC by smacker

Fix: https://github.com/src-d/code-annotation/issues/184

I couldn't test drone, but according to the rules there ( https://github.com/src-d/code-annotation/blob/master/.drone.yml#L84 ) macOs binary will be upload.

2018-03-06 12:20 UTC, dpordomingo approved these changes
LGTM

2018-03-06 12:20 UTC, dpordomingo requested changes
I leave this _red cross_ here to avoid merging this PR till we're ready for v0.0.5
(because we have no other way to test it :( )

2018-03-06 18:31 UTC, dpordomingo requested changes
Tested in drone and it failed:

when building in drone from `golang:1.9-alpine3.7` we got:
```bash
[...]
go-bindata \
	-pkg assets \
	-o ./server/assets/asset.go \
	build/static/... \
	build/*.json \
	build/*.png \
	build/*.svg \
	build/index.html

# github.com/src-d/code-annotation/vendor/github.com/mattn/go-sqlite3
../../vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:18:10: undefined: SQLiteConn
[...]
```
And no darwin binary created

2018-03-07 11:56 UTC, smacker commented
go-sqlite3 uses CGO. Even it's possible to cross-compile but way too complicated. Closing.

2018-03-07 11:56 UTC, closed without merging