Update browser title for each page
src-d/code-annotation pull request #95
Opened 2018-02-13 16:40 UTC by carlosms

Fixes #92 

Review.js does not work for now, but I hope it works after #94 is merged.

2018-02-13 16:47 UTC, smacker commented
hm... Do you think it would be better to use https://github.com/nfl/react-helmet ?
it would allow to use templates for titles and instead of juggling with componentDidMount/componentWillReceiveProps you can just put it in render function.

+ finish page is missed.

2018-02-14 10:21 UTC, carlosms commented
Thanks @smacker, I've pushed new code using react-helmet.

2018-02-14 10:24 UTC, smacker requested changes

2018-02-14 10:24 UTC, smacker commented on src/pages/Experiment.js
> +          <title>{`${this.props.name} | source{d} Code Annotation Tool`}</title>
please use `titleTemplate` to avoid copy-pasting suffix.

2018-02-14 15:42 UTC, dpordomingo approved these changes

2018-02-14 15:48 UTC, bzz approved these changes
LGTM

2018-02-14 16:14 UTC, smacker approved these changes

2018-02-14 17:00 UTC, bzz commented
@carlosms is there anything left before merging this guy?

2018-02-14 17:00 UTC, merged